apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  annotations:
    meta.helm.sh/release-name: jaeger-jaeger
    meta.helm.sh/release-namespace: jaeger
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: jaeger
    helm.toolkit.fluxcd.io/namespace: bigbang
    jaegertracing.io/operated-by: jaeger.jaeger-jaeger-jaeger-operator
  name: jaeger
  namespace: jaeger
spec:
  agent:
    config: {}
    options: {}
    resources: {}
  allInOne:
    annotations:
      sidecar.istio.io/inject: "true"
      traffic.sidecar.istio.io/includeInboundPorts: "16686"
    config: {}
    image: registry1.dso.mil/ironbank/opensource/jaegertracing/all-in-one:1.23.0
    labels:
      protect: keycloak
    options:
      collector:
        zipkin:
          host-port: :9411
      log-level: info
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
  collector:
    config: {}
    image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-collector:1.23.0
    maxReplicas: 5
    options:
      log-level: info
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
  ingester:
    config: {}
    options: {}
    resources: {}
  ingress:
    openshift: {}
    options: {}
    resources: {}
  query:
    image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-query:1.23.0
    labels:
      protect: keycloak
    options:
      log-level: info
    resources: {}
  resources: {}
  sampling:
    options: {}
  serviceAccount: jaeger-instance
  storage:
    cassandraCreateSchema: {}
    dependencies:
      resources: {}
    elasticsearch:
      storage: {}
    esIndexCleaner:
      enabled: false
      image: registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-es-index-cleaner:1.23.0
      numberOfDays: 5
      resources: {}
      schedule: 0 * * * *
    esRollover:
      resources: {}
    options:
      es:
        server-urls: https://logging-ek-es-http.logging.svc:9200
        tls:
          ca: /es/certificates/ca.crt
          enabled: "true"
    secretName: jaeger-secret
    type: elasticsearch
  strategy: allinone
  ui:
    options: {}
  volumeMounts:
    - mountPath: /es/certificates/
      name: certificates
      readOnly: true
  volumes:
    - name: certificates
      secret:
        secretName: elasticsearch-certificates
status:
  phase: Failed
  version: ""
