creation_rules:
  - encrypted_regex: "^(data|stringData)$"
    # Base is shared, you can add keys from each environment that uses base here
    pgp: F659930A04BB1155681F524C168B1E7E782DA128
#    ,ANOTHER_FALSE_KEY_HERE
# You can also isolate each key to specific directories by uncommenting the next 7 lines and adding the appropriate fingerprints
#  path_regex: base/.*
#- path_regex: dev/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: F659930A04BB1155681F524C168B1E7E782DA128
#- path_regex: prod/.*
#  encrypted_regex: '^(data|stringData)$'
#  pgp: ANOTHER_FALSE_KEY_HERE
