apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:D225HzIlLm7ZANCXeV3YzyNDb4jVAwxbkWBMuXWaU4IOFkPsL0dU0mczzZWoEXTLyCYSNigog9RpBORUT5gt0dT3hzPJjytAV39J1Bg5CKEQn41qncYPQv0T7SzdFG6hWFKeXQmizmPeBsWLMWj4g/QCky3+8Cv440tLNn9G,iv:0kgAclutT/rRlW5rlrv+hJTOr8/FaLUgqDL53pRkGrU=,tag:1wk4YdiGCA34GQ0uLIN0jQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T10:51:24Z"
    mac: ENC[AES256_GCM,data:VJ7ztVvIFyZ2zQu5prBtKY00E4HFgiHfc42iAA0PJLwoRbFS5nFM77RLYrEDi4vw86CTAETBv8dpY6ogIQ/Ak21KSST4Ih1K71My+SFrJB+Eu9wMGpFdwLFW/+Ntw1vjaiDqSQZfUHABVQxN+2oHZc9HXUZJvjPVVrmJW5wNgI8=,iv:8FeYxGv0oI+x+u3sRDwYk3SkjMKTxxnqO2F1MBbYIQg=,tag:NKCU+ABwW/nRckoIXpue0Q==,type:str]
    pgp:
        - created_at: "2021-07-06T10:51:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Pf7xAjIqJfARAAzaiU1mTNDeaaop0yzExXdsOxZf5UlxAM5QgiSap5FYin
            jzoP+RZc0duNNQw4chUH9g3un0ETJv6WJgVeyd0P3gy4bK7AWozVBu5rSxTWPNkC
            ToFtqrKNfHhd5X0Kx7FRU+vrKAlLrYc8Oj/dAOkElrljRma8bpyM/ALqnaVTsMQO
            6aa23JcYVbF8pwvhyU6sy0oF2SRMavDqscrebQicRGFTf68suUmpMiNELtc6b1NM
            mvUGwBd8sQJ9Gs2nEmjxpM8adxsJTGcXn1ktl3xrl5AAsMArwNaqeEeOl9+wXlty
            mFb6Q+W/+I991O3h5qwt3e8+TFpfzowpu4hbOppXto9cGdxiVh6ZhEE1mf/jg5bH
            6vPyps0OFRNygHIU+xVqVtsnq94iuEXAQ/SVqK/hdUWHcOoKyZtoQDvs0kjLWgJR
            CYLcwVkU9M7o+BiWi15pFrxXX3RAQmX1AzoNidkJps9/lm4vup3yb5sMPv9ooAEg
            c7cAqsMZgcQWqvk8SXnwauJ6wOYNpU2z8tIxbiylwm0AiGBLuvNO9MyzWX2rVHqe
            xhVvosp6KOa3D4Lq/HTBpfm3kxj1Q8StJOwqfxVHso4AC0OzOWrfl7wZBD43c56T
            0LCQzd7LOGvTpFrWQ3WQxiGulKDgeW6WzIHnHS6C7vGvYDql3WwNSBxzV2uzKL/S
            XgH2thYdlEH2Mt6RWqUp5Jjt9nCgKfLc5/PZ2PEEzDgHPRjTbJfvbP0s/zyaUxv8
            61X2Hwrj7dBn6z2IziInIySLu6p/CfLMvQ1Sckc57TTfVLZpOczw/621Tyr+oGI=
            =7e+M
            -----END PGP MESSAGE-----
          fp: 414F9C9912C2CC016966627C63C2CD58E2E775DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
