apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:p0hso6ahyGOG25bsjg6E06NgNQ2NtRz+o2ulNvWVY+wCHlNkxVpWXixGXZvlscSkLYPxCU16YC2H1RCXmA26wM2CFloPMMmQwcAbn4UFlly7UOf+RHgliwtswmQVM77HJSMl5AHsx4kW7REvoZJV1GbgPkxMmQoSEQXdxnzB,iv:KSquPBfEUHZB4CrX7vz1qDI+p6Hmo8oeNIfa0AoMpds=,tag:1jqfc5lDz98pSjaH0DTmDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-06T10:47:41Z"
    mac: ENC[AES256_GCM,data:vpfLFL1MJgME7ZWQqdBYzzqv8YeW0jB694sG9MFUzXilg0XJ5NRYvGHVhxiQUKe+u5ipzyiOpoOmogCsovX61cgN3ppID4U8jPZgyKpB/bP93pveoFzON7hBwrNyId8Wn1S/kRS0eFvuX7lcjTORxR0ryi+BJg+7x0M/YkitxS8=,iv:ghBnO+E8Z7fV8MRi6PscHg0MAe8ZBC+ioekB4L3YmwM=,tag:0m+0d0IUfkNeqFSpeMAejA==,type:str]
    pgp:
        - created_at: "2021-07-06T10:47:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7Pf7xAjIqJfARAAn/Rq3FvaCTtpsT/T93ncO86NRIgW6iwMyPDDjNvjWBsE
            uYgpUAXXSvQSInfNZxasKvpKrkGXqdFhanGvfvvlfVTlEBR9uMarQkAAeKCWNTu6
            lkQcf+FyoMMT6bvezAmf33YFRyCVhyWRRbTHfAanErRP8VxeOszjGMUXKBZb6RAP
            q8tiGvuBw6zwmmbBuF/wEUmNif8BIwFvTSJSyUOvbAd+TK60LgClYs3wSBrP9yQm
            9VuJbnlHcc0wV3RvYO1ZMAR57c9cL89xV6XouYHw7+gNGwMxv81+zjtWMruthI97
            qP5HjFrKPmiB0cFlRpf+05/U4MjHejLAGr/8H8Y58sFyQlAgNUlabVvhKCdD2DZw
            TPTifU9CGoJtuw6VTJNwP9DK/QnKMDEL2m1bXSf5j5NMKWzjTBGGYDTIcMgfyJpT
            zXjxL57fCaJqasMGOlEIuloUIR8n41efc7tDZzk3wFX+HfKmri6R2trTpfa2OQ+L
            AAX2bIr/+R1MqZb0k1yNybyYUyORyqesJZQ6PvyJIXquLsiXwADj1hOVkFr4p9N/
            Pgut80egpxRxVS0IsFK0uDeoNisaUd5vAGQagRmbvXnLCUSSV5mN38nIbrp+NjbZ
            3fB2z23Z6DJexbTd9qRCHvcE6h+BiLckHbzDN10ricA0RighDTCuAwQg+ZRLBHvS
            XgFHuDSP9Yk3ca0jT0Pog086E3JCjvd/qP4yueaNihSaQGCIfOyh5x7HOtRw56p2
            U3JZgny/Vwtg/Pxh9RQkSoyVYi3qlh4xvvd/c2/NHhdA9EmNPSmPW+kz1hOFz/c=
            =mWu8
            -----END PGP MESSAGE-----
          fp: 414F9C9912C2CC016966627C63C2CD58E2E775DC
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
