apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:U0mruuGMeL4agkPMR/aYNxItkYXQLna28WlMXlCmyDi/oDlMWZ9fFcLKMC3gliyGJIbEISNE5TMEjsTShFT8XJDWZQvFZfcmg0uw1i989j8PjgkV6O1vJtYKWORhyWvuF+t37P0ffK8aAp2/lSat8khvA9OmCUY=,iv:1kMZboaqxP9oushDazNjUrAEVQ2zJR7Hq5+Kx2zAzxE=,tag:/VksXqbh8Izm5tuwk0kA9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-30T14:48:14Z"
    mac: ENC[AES256_GCM,data:2edwd+tBCUD1d75eDA+tywg60XK0xgRu1F4jbfqaFbbLjg8RKvF7Cq0DOrczYjsHlyUOMf3XK2HQjglwySiEaByTsYZTiC0Wxmxd80IWnSjLr+ivT6/AgpawAn8tZcmceJqbKVHJP9CJL4C7lx41PBfgmPeHR5JPBCyo1p5LQ2Q=,iv:Q+ybL4nBQgipUSOyYwnA9Xc6ib00suCLknE7/jBrDd0=,tag:b2YAFarmoImViR+EKh/WSg==,type:str]
    pgp:
        - created_at: "2021-06-30T14:47:50Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6V9LpYPYUs6AQ/9FtldmC1B0Np4ucE6KfIbVvesiEEU8TXHco1Zhn6hXhoF
            +i0qdviCaYHz7PaF3FRWKhzzHuxWGOeCdA8Z7Wyp/XuC7AXzBGqhg62vW7HzPltG
            CFbT4Zm6OCXbCVzkKgZa2X2AjK7p6PtcEjnzV8EiibiT3/ollz/dAWJHBu0h+RgK
            5feyPePHuIUAQp2GouVcxcHATpfgbY/7ooeJc/GENz9UvzCssYOGa7VHfs4wO5Ir
            jSUDPyySyhzB+JE+Caq255OnQDaHrreuJGRyxCDH8BZw0XZ/HQOepvHuXDgMtyOl
            C4/jlVau4sDEzm9Q2Ypqzy2TlaI4gYSnpyu1GQ0RYyMM9Rs1aPvP4njD6mds6peK
            5x9OrY1SDmE9/kUcAd5T8KBuN2h0tL2DGWzF7se+3sOFaiAzMjodoZH9QtD401FU
            dmmcykiIVpSUz11fGxCkRMqvcvv+gLQ3YwRaFDmHt9PxYeKqohrWPGWzvrG0TZrd
            7JSC9TfyqywvF5pdE4wpKQ3IXC+St0nXw1Yx+tIvljuyF7JJSMYKoXoABwD49YyY
            /jmT61UY+92omhNaeWMFDUNEUCOnTQvTi4Af1K2Cn6UH4tpiyv6b4URuKMiiL+RD
            o9jx2gBiW2cTHhUzZ5zEfzv27avQ8kFlkO7YHVst/l1SII7CJVxQ43PH1Ffb0KfS
            XgHKt1i0ouQSnuE8O05QQLw4Kv802JBgYQ3Wq1FasGT1lEaYtkO0Qoln13XcYgOm
            VX6Ole7Egi+W0LU60l0O6PL1tsGkOTHGPStcmF9iqV5hdqsBfn4r7LIKtkf+pZQ=
            =WUb5
            -----END PGP MESSAGE-----
          fp: F659930A04BB1155681F524C168B1E7E782DA128
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
