apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:IqfU8EXEdIvJEuJMe21JWyybMY3jymZNX86LUySCI+nT/s9x/h5isMfaYcCqMEwtd7pNDv0qGwADiLNRxGhJVcCAh4TyKfDm4RywAwF5SqpiZikAeAOClm5Ydx5/q7YxNfPYl8zs9nyFnWENI+9wxcPpRIr0GUw=,iv:zt0VpcnmiBhFfq9ipOEEa2aTGhHOtGYOKkNFh2wAHsA=,tag:sVWWXhqoNyR3gerp25Numg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-02T15:15:17Z"
    mac: ENC[AES256_GCM,data:0f6SuZXuKTW6K5xsu+iesNhVjIOQQpV292z6D0rf2vCEhauAxV1VpdSx+0htDuX9ZQcXdfSFptCZbi6p5AKmWaU3RVTfvfUe+LykpXXADDoO8jeYn9y7v9eDUDp2aEKefnkEr22Cho6aCYofZ3jlDGfJnVJy78oJI7YbLOTAAzg=,iv:ondQzdFxbxEL2k7SF3zBckpisehdZ2A2JzHr1Iu0Epw=,tag:VnyeE1A+uWTo7TqgX5G+2w==,type:str]
    pgp:
        - created_at: "2021-07-02T15:15:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6V9LpYPYUs6AQ/+P+Ni1/WiLZdpcrF9O8tu7Uf/GWSNGM9B3YFwGSNoV4sZ
            uXI7VkLxJ1jFdEJ4tJ7aP+Yqpsx28u3ojJBiDFvCEBIizhWGnZs5/rbXstkWN5iU
            iY/NTm5FOUn8Oe2NcHUAOJ9OLGh2nxyH4koE8hHFX0uSlaVZdieqfB2og3LyOOw1
            DhBGvPmIowY4JMJLCVKHryRneAivMBaBFx0OaglrGSdnyxKj8E8UZm/5VjMMO0rz
            bLq9SwjbbyVhO9bgXbtjxZxJkVKY8lvbpWFJyfnzh+tdraEBPfoivS7EEDq/wGvk
            iSszAbO+dU6HUUh7q4GY/qJ9ARdIhAQDGgib4BmI6XVZKyxZidvJLvFPnIv4Eec9
            PErxJtP+uidyw8BkLYVKfcuslanNWOiuEq+ED3x1pldEB/WlxYBFfok1rRsCObDX
            ymG3D/ZFp5xDN5mDXIcps3W8tg2l9b+cdgRSVu5zyGINbtaH1XvJTtz7cSVgATuL
            Jwh+AbKRyE0x5XZ7FmB4SHAHf8a0VdFn1X7zRZ17oN2bPnsq9jMrvMd8Zf2LCJym
            xCRAPX9ybyV4GSptNnlccI21mz1rkBHltwvOxgULY9qmp+m4L47EKKOHuSAuF1Ov
            lryYOo3ogqkANYcLVwHgUBZx01LLamlUkYokcHh7Z1gw16VDSXs2zNaDdKCAyxHS
            XgH7BlrnFPyA2LKH8zq3z4Ko0l8+i+3XzpAWluQ8l1lx9yK7f8hQctcpHRJIHUH7
            2nfbSUJ4HlSBtGQoo22P42RIlTZ2VVQIO1Jy/0xoAUGo1wDMCwQNe3Z3WshbHxI=
            =725e
            -----END PGP MESSAGE-----
          fp: F659930A04BB1155681F524C168B1E7E782DA128
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
